CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    public_key CLOB NOT NULL,
    private_key CLOB NOT NULL
);